-- Mostrar información del equipo con el ‘valor plan’ más caro disponible.
SELECT EQU_NOMBRE, EQU_VALOR_PLAN
FROM EQUIPO E
WHERE E.EQU_VALOR_PLAN = (
	SELECT MAX(EQU_VALOR_PLAN)
	FROM EQUIPO)

-- Mostrar información del último contrato realizado.
SELECT C.CON_CORREL, E.EJE_NOMBRES, E.EJE_PATERNO, E.EJE_MATERNO, P.PLA_NOMBRE, EQ.EQU_NOMBRE, CL.CLI_RUT, CL.CLI_NOMBRES, CL.CLI_PATERNO, CL.CLI_MATERNO
FROM CONTRATO C
JOIN EJECUTIVO E ON C.EJE_NUMERO = E.EJE_NUMERO
JOIN PLAN_MOVIL P ON C.PLA_CODIGO = P.PLA_CODIGO
JOIN EQUIPO EQ ON C.EQU_CODIGO = EQ.EQU_CODIGO
JOIN CLIENTE CL ON C.CLI_RUT = CL.CLI_RUT
WHERE C.CON_FECHAINI = (SELECT MAX(CON_FECHAINI) FROM CONTRATO)

-- Muestre la información de los clientes (rut , nombre y apellidos) que tienen contrato vigente con la compañía.
SELECT DISTINCT CL.CLI_RUT, CL.CLI_NOMBRES, CL.CLI_PATERNO, CL.CLI_MATERNO
FROM CONTRATO C
JOIN CLIENTE CL ON C.CLI_RUT = CL.CLI_RUT
WHERE C.CON_FECHAFIN IS NULL

-- Mostrar información de clientes (rut , nombre y apellidos y Nro. de contrato), que han pagado atrasada su cuenta el mes de Febrero de 2011
SELECT CL.CLI_RUT, CL.CLI_NOMBRES, CL.CLI_PATERNO, CL.CLI_MATERNO, C.CON_CORREL, EP.EPA_FECPAGO, EPA_FECVENCE
FROM CONTRATO C
JOIN CLIENTE CL ON C.CLI_RUT = CL.CLI_RUT
JOIN ESTADO_PAGOS EP ON C.CON_CORREL = EP.CON_CORREL
WHERE EP.EPA_FECPAGO > EP.EPA_FECVENCE
AND EP.EPA_FECVENCE BETWEEN '2011-02-01' AND '2011-02-28'

-- Mostrar información de los contratos realizados por los ejecutivos que pertenecen a la sucursal 1.
SELECT C.CON_CORREL, C.CLI_RUT, C.EQU_CODIGO, C.PLA_CODIGO, C.CON_FECHAINI, C.CON_FECHAFIN, E.EJE_NOMBRES, E.EJE_PATERNO, E.EJE_MATERNO
FROM EJECUTIVO E
JOIN CONTRATO C ON E.EJE_NUMERO = C.EJE_NUMERO
JOIN SUCURSAL S ON E.SUC_CORREL = S.SUC_CORREL
WHERE S.SUC_CORREL = 1

-- Mostrar información de los clientes con contrato vigente que actualmente tengan el equipo más caro disponible para el valor plan.
SELECT CL.CLI_RUT, CL.CLI_NOMBRES, CL.CLI_PATERNO, CL.CLI_MATERNO, CL.CLI_EMAIL, CL.CLI_FONO
FROM CLIENTE CL
JOIN CONTRATO C ON CL.CLI_RUT = C.CLI_RUT
JOIN EQUIPO E ON C.EQU_CODIGO = E.EQU_CODIGO
WHERE C.CON_FECHAFIN IS NULL
AND E.EQU_CODIGO = (
	SELECT EQ.EQU_CODIGO
	FROM EQUIPO EQ
	WHERE EQ.EQU_VALOR_PLAN = (SELECT MAX(EQU_VALOR_PLAN) FROM EQUIPO))

-- Mostrar la cantidad de contrato realizados por cada ejecutivo que pertenece a la sucursal 1
SELECT E.EJE_RUT, E.EJE_NOMBRES, E.EJE_PATERNO, E.EJE_MATERNO, COUNT(*) AS NUM_CONTRATOS
FROM EJECUTIVO E
JOIN CONTRATO C ON E.EJE_NUMERO = C.EJE_NUMERO
JOIN SUCURSAL S ON E.SUC_CORREL = S.SUC_CORREL
WHERE S.SUC_CORREL = 1
GROUP BY  E.EJE_RUT, E.EJE_NOMBRES, E.EJE_PATERNO, E.EJE_MATERNO
ORDER BY NUM_CONTRATOS DESC

-- Mostrar la cantidad de contrato realizados por cada SUCURSAL
SELECT S.SUC_NOMBRE, COUNT(*) AS CONTRATOS_POR_SUCURSAL
FROM SUCURSAL S
JOIN EJECUTIVO E ON S.SUC_CORREL = E.SUC_CORREL
JOIN CONTRATO C ON E.EJE_NUMERO = C.EJE_NUMERO
GROUP BY S.SUC_NOMBRE

